### ISSUE TITLE
Unexpected Value Exception

### ISSUE THREAD

**Issue by mamulasa** [stevenmaguire/yelp-php#14]
Hi Steven, 
I am running into some exception.
I have used your example code "$results = $client->getBusiness('union-chicago-3');"

and my result is:
"The Response content must be a string or object implementing __toString(), "object" given."

by dd($results) I get some response but there is also a hint:

"Error: Parse error on line 1:
{#228 ▼  +"rating": 
-^
Expecting 'STRING', '}'"

![bildschirmfoto 2016-08-06 um 00 32 04](https://cloud.githubusercontent.com/assets/13347408/17452184/3d0c329c-5b6d-11e6-90e9-773796ab4e48.png)

Any Idea what's wrong?

Thanks in advance.

**Comment by stevenmaguire** [comment]
After reviewing the information you've provided here, I believe that the issue is not with the yelp-php package, and instead with the framework you are using. Because you mention using `dd($results)` I am assuming you are using Laravel? If so, the error `"The Response content must be a string or object implementing __toString(), "object" given."` makes sense to me if you are attempting to send the yelp-php client result directly to the Response object as is. The result from yelp-php will be an Object and the Response expects a string. If this is your intention, I would suggest making some changes to your framework code to coerce the yelp-php result into a compatible format.
