### ISSUE TITLE
TOKEN_MISSING

### ISSUE THREAD

**Issue by motoservo** [stevenmaguire/yelp-php#29]
I've just attempted to use the Yelp Fusion API (and this package) for the first time.

Seems pretty straight forward, and I don't think I was confused about any of the setup except for the use of Guzzle.

1. I created my app at the Yelp dev portal and obtained my API key.
2. I entered that key where it belongs in the options array.
3. Created the new client using client factory (copy pasted from here)
4. Created a new Guzzle client but having never used Guzzle before I left the config as is (commented).
5. I passed $specialHttpClient to setHttpClient() (again, just copy and pasted) while also trying to get a business with the chained method.

The error I get is a 401.

I ErrorException (E_ERROR)
Client error: `GET https://api.yelp.com/v3/businesses/beach-buggy-santa-monica` resulted in a `401 Unauthorized` response: {"error": {"code": "TOKEN_MISSING", "description": "An access token must be supplied in order to use this endpoint."}}...

Please advise.
Troy

**Comment by stevenmaguire** [comment]
@motoservo Can you please show the code that you are using to configure your yelp client? "just copy and pasted" is not enough for me to see what you are actually doing and I can't help troubleshoot your problem without first understanding exactly what you are doing.

**Comment by motoservo** [comment]
Thanks for the quick reply.

Here is the relevant code…
https://gist.github.com/motoservo/83ff3246b216ab2f658efb10c65ffd7c

**Comment by stevenmaguire** [comment]
Why do you need a `$specialHttpClient`? Does it work if when you don't define your special API client? It should. When you define your own httpClient you need to handle your own configuration, which is why it is indicated as "Advanced" configuration. If you don't have a compelling reason to do so, don't and it should work just fine.

Also, unrelated to your error and based on what your use case appears to be you only need to define `$options['apiKey']` in your $options array. The other two are not needed.

**Comment by motoservo** [comment]
Okay, I simplified it (had done that earlier but got an error, but now I see why and have fixed that).

Getting the object returned from the reviews() method so I've print_r and studying how to get at the data I need. I think I've got it from here and thanks for your quick replies.

**Comment by stevenmaguire** [comment]
Awesome. Great news. I am glad I was able to help. Good luck!
